/* 프로젝트 목록 — mock 미디어·공개 레포가 있다고 가정한 풍성 미리보기 버전.
 * 실제 에셋으로 교체: assets/mock/*.svg → 스크린샷/영상 썸네일, youtube URL 교체
 */
window.projects = [
  {
    tier: "featured",
    title: "FBNeo Agent",
    summary: "Agent가 에뮬레이터를 프레임 단위로 제어·캡처하는 런타임 계측 파이프라인",
    detail:
      "MAME 제어가 어려워 FBNeo를 포크해 -agent와 5채널 SHM을 붙였습니다. 화면·입력·메모리를 Agent가 다루게 해, 이후 캡처·훈수형 플레이의 기반이 됐습니다.",
    stack: ["C++", "FBNeo", "Shared Memory", "Python"],
    repo: "https://github.com/buc89l2nb41/FBNeo-Agent",
    demo: null,
    youtube: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
    images: [
      "./assets/mock/fbneo-01.svg",
      "./assets/mock/fbneo-02.svg",
      "./assets/mock/fbneo-03.svg",
    ],
  },
  {
    tier: "featured",
    title: "Godot NNUE Prompt Chess",
    summary: "LLM 코칭 + Stockfish 후보 게이트로 환각 수를 막는 Agent 플레이",
    detail:
      "프롬프트 코칭을 붙이되, LLM이 낸 수를 보드에 바로 올리지 않고 엔진 MultiPV 후보만 허용합니다. make_move가 최종 게이트라 불법·엉뚱한 수를 차단합니다.",
    stack: ["Godot", "GDScript", "Stockfish", "AI"],
    repo: "https://github.com/buc89l2nb41/GodotNnuePromptChess",
    demo: null,
    youtube: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
    images: [
      "./assets/mock/chess-01.svg",
      "./assets/mock/chess-02.svg",
      "./assets/mock/chess-03.svg",
    ],
  },
  {
    tier: "featured",
    title: "Low Poly Cultivar",
    summary: "Trellis 메시를 여러 LOD로 깎고 4방향 유사도로 자동 고르는 툴",
    detail:
      "GrowRoll에서 Trellis 메시가 무거워 gltfpack 파라미터를 실험하다, 프리셋 비교 UI와 전후좌우 유사도 자동 선택을 만들었습니다. 에셋 생성 파이프라인의 성능 병목을 툴로 푼 사례입니다.",
    stack: ["TypeScript", "Three.js", "gltfpack"],
    repo: "https://github.com/buc89l2nb41/LowPolyCultivar",
    demo: null,
    youtube: null,
    images: [
      "./assets/lowpoly/01-home.png",
      "./assets/lowpoly/03-after-generate.png",
      "./assets/lowpoly/04-mid.png",
      "./assets/lowpoly/05-bottom.png",
    ],
  },
  {
    tier: "featured",
    title: "TranslationChat",
    summary: "배포된 AI 번역·대화 서비스",
    detail:
      "Agent API로 실제 쓸 수 있는 웹 서비스를 만들고 배포했습니다. 웹·API 쪽 실행력의 증거로 둡니다.",
    stack: ["JavaScript", "AI", "Fastify"],
    repo: "https://github.com/buc89l2nb41/TranslationChat",
    demo: "https://translationchat.onrender.com",
    youtube: null,
    images: ["./assets/mock/trans-01.svg", "./assets/mock/trans-02.svg"],
  },
  {
    tier: "featured",
    title: "AgentPlay",
    summary: "에뮬 위 훈수형 AI 플레이 런타임 (미완)",
    detail:
      "RL이 아니라 Gradio/REPL 코칭 + AUTO로 피벗했습니다. SHM·정책 틱 골격은 있으나 명령 추종 품질은 아직 다듬는 중입니다.",
    stack: ["Python", "FBNeo", "Gradio", "VLM"],
    repo: "https://github.com/buc89l2nb41/FBNeo_AgentPlay",
    demo: null,
    youtube: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
    images: ["./assets/mock/agentplay-01.svg", "./assets/mock/agentplay-02.svg"],
  },
  {
    tier: "other",
    badge: "서비스",
    title: "AI Playlist Creator",
    summary: "Agent API로 플레이리스트를 구성하는 웹 서비스",
    stack: ["JavaScript", "AI"],
    repo: "https://github.com/buc89l2nb41/AiPlaylistCreator",
    demo: "https://ai-playlist-creator-eight.vercel.app",
    youtube: null,
    images: ["./assets/mock/playlist-01.svg"],
  },
  {
    tier: "other",
    badge: "서비스",
    title: "PersonaChat",
    summary: "페르소나 기반 채팅 클라이언트·서버",
    stack: ["TypeScript", "AI"],
    repo: "https://github.com/buc89l2nb41/PersonaChat",
    demo: "https://persona-chat-gamma.vercel.app",
    youtube: null,
    images: ["./assets/mock/persona-01.svg"],
  },
  {
    tier: "other",
    badge: "툴",
    title: "Prompt Asset Forge",
    summary: "프롬프트→이미지→메시 배치 생성 파이프라인",
    stack: ["Python", "AI"],
    repo: "https://github.com/buc89l2nb41/PromptAssetForge",
    demo: null,
    youtube: null,
    images: ["./assets/mock/forge-01.svg"],
  },
  {
    tier: "other",
    badge: "툴",
    title: "ModelToSprite",
    summary: "3D 포즈→스프라이트 툴 MVP",
    stack: ["TypeScript", "Three.js"],
    repo: "https://github.com/buc89l2nb41/ModelToSprite",
    demo: null,
    youtube: null,
    images: ["./assets/mock/model-01.svg"],
  },
  {
    tier: "other",
    badge: "프로토타입",
    title: "GrowRoll",
    summary: "Trellis 기반 3D 수집·성장 루프",
    stack: ["TypeScript", "Web"],
    repo: "https://github.com/buc89l2nb41/GrowRoll",
    demo: "https://grow-roll-client.vercel.app",
    youtube: null,
    images: [
      "./assets/growroll/01.png",
      "./assets/growroll/02.png",
      "./assets/growroll/03.png",
    ],
  },
  {
    tier: "other",
    badge: "프로토타입",
    title: "GGPO Webgame",
    summary: "격투 웹 프로토타입",
    stack: ["TypeScript", "Game"],
    repo: "https://github.com/buc89l2nb41/GGPO_Webgame",
    demo: "https://ggpo-webgame.vercel.app",
    youtube: null,
    images: ["./assets/mock/ggpo-01.svg"],
  },
  {
    tier: "other",
    badge: "실험",
    title: "Cadillacs Capture",
    summary: "Godot + FBNeo 캡처 연동 실험",
    stack: ["Godot", "FBNeo"],
    repo: "https://github.com/buc89l2nb41/CadillacsCapture",
    demo: null,
    youtube: null,
    images: ["./assets/mock/cadillacs-01.svg"],
  },
  {
    tier: "other",
    badge: "실험",
    title: "DiffusionGen",
    summary: "스프라이트 생성 파이프라인 실험",
    stack: ["Python", "Diffusion"],
    repo: "https://github.com/buc89l2nb41/DiffusionGen",
    demo: null,
    youtube: null,
    images: ["./assets/mock/diffgen-01.svg"],
  },
];
